apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-demo
spec:
  project: default
  source:
    repoURL: git@github.com:brokenlance/argo.git
    targetRevision: HEAD
    path: kube-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
