FROM alpine:3.18.2
RUN   apk update                        \
   && apk upgrade                       \
   && apk add ca-certificates           \
   && update-ca-certificates            \
   && apk add --update openjdk17 tzdata \
   && rm -rf /var/cache/apk/*
